spring:
  application:
    name: rabbitmq.consumer.two

#  rabbitmq:
#    listener:
#      simple:
#        prefetch: 1
  rabbitmq:
    addresses: "localhost:5672"
    # host: 127.0.0.1
    # port: 5672
    # default are guest/guest
    username: admin
    password: admin