spring:
  application:
    name: rabbitmq.consumer

  rabbitmq:
    addresses: "localhost:5672"
    username: test
    password: test
    listener:
      simple:
        # needed for retry consumer
        acknowledgment-mode: manual
