spring:
  application:
    name: rabbitmq.consumer

  rabbitmq:
    addresses: "localhost:5672"
    username: test
    password: test
    listener:
      simple:
        # needed for retry consumer
#        acknowledgment-mode: manual
        retry:
          # must use automatic ack mode
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2

