spring:
  application:
    name: rabbitmq.producer

  rabbitmq:
    addresses: "localhost:5672"
    # host: 127.0.0.1
    # port: 5672
    # default are guest/guest
    username: test
    password: test
